
language: python
python:
  - "2.6"
  - "2.7"
# MySQL in lib doesn't build from pip in Python 3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "pypy"
#  - "pypy3"

sudo: required

env:
  - DEBUG=1

notifications:
  email: false

branches:
  only:
    - master

#install:
#  - make

#script:
#  - make test

#after_success:
#  - coveralls

sudo: required
